### ISSUE TITLE
Why it fails in GET?

### ISSUE THREAD

**Issue by eventang2015** [connorjburton/hmac-auth-express#82]
Hi, 
this package works well in POST, but it always fails in GET.
i'm using axios interceptors,  code snippet:

`instance.interceptors.request.use((config: AxiosRequestConfig) => {
    const time = Date.now().toString()
    const httpMethod = config.method!.toUpperCase()
    const requestPath = config.url!

    let digest = generate('secret', 'sha256', time, httpMethod, requestPath, config.data).digest('hex')
    if (httpMethod === 'GET') {
        digest = generate('secret', 'sha256', time, httpMethod, requestPath, {}).digest('hex')
    }
    const hmac = `HMAC ${time}:${digest}`

    config.headers!.Authorization = `${hmac}`
    return config
}, err => {
    return Promise.reject(err)
})`

my requests:
GET `/order/:key`

GET `/orders?pageindex=1&pagesize=50`

**Comment by connorjburton** [comment]
Hey,

I don't see much wrong with your code snippet. It likely depends on how your server is setup and what kind of body parser you are using.

As per [the documentation](http://expressjs.com/en/api.html#express.json), if you use the built-in body parser `request.body` will be `{}` if there is no body or the content-type header does not match. That's why we expect `{}` for plain GET requests.

In this case, you may be using a different body parsers (or none at all) on that route, which means you are going to want to pass `undefined` as the 6th argument of `generate`

```
let digest = generate('secret', 'sha256', time, httpMethod, requestPath, config.data).digest('hex')
if (httpMethod === 'GET') {
    digest = generate('secret', 'sha256', time, httpMethod, requestPath).digest('hex')
}
```

The easiest way to confirm is to check what body parsing you are doing and also log out `request.body` in the middleware which should be located at `node_modules/hmac-auth-express/dist/generate.js`

If you are still struggling then please create a repo with a minimum example so I can take a look.

Thanks!

**Comment by eventang2015** [comment]
@connorjburton I was using body-parser, after  using express.json() instead of body-parser, now it works. thank you very much.
